# Generated by Django 5.2.17 on 2026-09-18 19:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BayAreaGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='1×1 km grid cell polygon in WGS84 (EPSG:4326).', srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(help_text='Pre-computed centroid for fast spatial lookups.', srid=4326)),
                ('row', models.IntegerField(help_text='Grid row index (0-based, south to north).')),
                ('col', models.IntegerField(help_text='Grid column index (0-based, west to east).')),
            ],
            options={
                'verbose_name': 'Bay Area Grid Cell',
                'verbose_name_plural': 'Bay Area Grid Cells',
                'indexes': [models.Index(fields=['row', 'col'], name='grid_bayare_row_aed7e3_idx')],
                'unique_together': {('row', 'col')},
            },
        ),
        migrations.CreateModel(
            name='TerrainFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.FloatField(help_text='Elevation in meters above sea level (USGS DEM).')),
                ('slope', models.FloatField(help_text='Terrain slope in degrees (0–90).')),
                ('aspect', models.FloatField(help_text='Terrain aspect in degrees (0–360, N=0).')),
                ('hillshade', models.FloatField(help_text='Hillshade value (0–255) for visualization.')),
                ('powerline_dist_km', models.FloatField(blank=True, help_text='Distance to nearest CA Energy Commission powerline in km. Ignition risk proxy from Malik et al. (2021). DEFERRED: ML team to decide if needed.', null=True)),
                ('grid', models.OneToOneField(help_text='The grid cell this terrain data belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='terrain', to='grid.bayareagrid')),
            ],
            options={
                'verbose_name': 'Terrain Feature',
                'verbose_name_plural': 'Terrain Features',
            },
        ),
        migrations.CreateModel(
            name='VegetationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date this vegetation measurement was captured.')),
                ('ndvi', models.FloatField(help_text='Normalized Difference Vegetation Index (-1 to 1). High values indicate dense green vegetation.')),
                ('evi', models.FloatField(blank=True, help_text='Enhanced Vegetation Index. More sensitive than NDVI in dense canopy.', null=True)),
                ('ndwi', models.FloatField(blank=True, help_text='Normalized Difference Water Index. Proxy for fuel moisture content.', null=True)),
                ('grid', models.ForeignKey(help_text='The grid cell this vegetation data belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_indices', to='grid.bayareagrid')),
            ],
            options={
                'verbose_name': 'Vegetation Index',
                'verbose_name_plural': 'Vegetation Indices',
                'indexes': [models.Index(fields=['date'], name='grid_vegeta_date_1a7388_idx'), models.Index(fields=['grid', 'date'], name='grid_vegeta_grid_id_872627_idx')],
                'unique_together': {('grid', 'date')},
            },
        ),
    ]
