# Generated by Django 5.2.17 on 2026-09-18 19:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official shelter name.', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Shelter GPS coordinates (WGS84).', srid=4326)),
                ('address', models.TextField(blank=True, help_text='Full street address.')),
                ('county', models.CharField(blank=True, help_text='Bay Area county name.', max_length=100)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum shelter capacity (persons). Null if unknown.', null=True)),
                ('source', models.CharField(default='FEMA', help_text='Data source (FEMA or CalOES).', max_length=50)),
            ],
            options={
                'verbose_name': 'Emergency Shelter',
                'verbose_name_plural': 'Emergency Shelters',
                'indexes': [models.Index(fields=['county'], name='telemetry_e_county_9329ce_idx')],
            },
        ),
    ]
