# Generated by Django 5.2.17 on 2026-09-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=20)),
                ('ml_adapter_response_code', models.IntegerField(blank=True, null=True)),
                ('predictions_written', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Harvest Run',
                'verbose_name_plural': 'Harvest Runs',
                'ordering': ['-run_at'],
            },
        ),
    ]
