"""
Harvester Integration Tests — Fight Fire With AI

Tests the full trigger_daily_inference() happy path:
  1. Mocks the FastAPI ML Adapter HTTP response.
  2. Verifies PredictionPolygon rows are written to the test PostGIS database.
  3. Verifies the full GeoJSON is written to the Redis cache.

ffwai-django-celery skill: require unit tests for Celery task failure states
and happy-path verification that predictions land in DB + Redis.

Design Doc §11.1 AI & Data Pipeline Testing: verify mock mode serves fixture
and that data ingestion writes correct prediction rows.

Run with:
    cd backend && pytest harvester/tests.py -v
"""

import json
from unittest.mock import patch, MagicMock

import pytest
from django.core.cache import cache

from harvester.tasks import trigger_daily_inference, store_geojson_result, CURRENT_RISK_CACHE_KEY


# ---------------------------------------------------------------------------
# Mock GeoJSON fixture (matches bay_area_fixture.json output contract)
# ---------------------------------------------------------------------------

MOCK_GEOJSON_RESPONSE = {
    "type": "FeatureCollection",
    "metadata": {
        "timestamp": "2026-09-23T06:00:00+00:00",
        "source_model": "mock",
        "mock": True,
    },
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [[
                    [-122.22, 37.05], [-122.2143, 37.05],
                    [-122.2143, 37.0545], [-122.22, 37.0545],
                    [-122.22, 37.05],
                ]],
            },
            "properties": {
                "grid_id": 1001,
                "fire_probability": 0.91,
                "source_model": "mock",
                "timestamp": "2026-09-23T06:00:00+00:00",
                "horizon_hours": 24,
                "w_unet": 0.8,
                "model_version": "v1.0"
            },
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [[
                    [-122.2143, 37.05], [-122.2086, 37.05],
                    [-122.2086, 37.0545], [-122.2143, 37.0545],
                    [-122.2143, 37.05],
                ]],
            },
            "properties": {
                "grid_id": 1002,
                "fire_probability": 0.45,
                "source_model": "mock",
                "timestamp": "2026-09-23T06:00:00+00:00",
                "horizon_hours": 24,
                "model_version": "v1.0"
            },
        },
    ],
}


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.mark.django_db(transaction=True)
def test_trigger_daily_inference_happy_path():
    """
    Verifies the full trigger_daily_inference() happy path:
      - Seeds the BayAreaGrid rows required to satisfy the FK constraint on
        PredictionPolygon.grid_id (grid_id 1001 and 1002 must exist before
        the task can write predictions for them).
      - Mocks the FastAPI ML Adapter to return MOCK_GEOJSON_RESPONSE.
      - Asserts that PredictionPolygon rows are created in the test DB.
      - Asserts the full GeoJSON is stored in the Redis cache under
        the correct key.

    Design Doc §11.1 AI & Data Pipeline Testing.
    ffwai-django-celery skill: happy-path verification, predictions in DB + Redis.
    """
    from django.contrib.gis.geos import Polygon, Point
    from grid.models import BayAreaGrid
    from predictions.models import PredictionPolygon

    # Seed BayAreaGrid rows that the FK constraint on PredictionPolygon.grid_id
    # requires. In production these are generated by `python manage.py generate_grid`.
    cell_polygon = Polygon((
        (-122.22, 37.05), (-122.2143, 37.05),
        (-122.2143, 37.0545), (-122.22, 37.0545),
        (-122.22, 37.05),
    ), srid=4326)
    grid_1001 = BayAreaGrid.objects.create(
        id=1001, geometry=cell_polygon,
        centroid=Point(-122.215, 37.055, srid=4326),
        row=0, col=0,
    )
    grid_1002 = BayAreaGrid.objects.create(
        id=1002, geometry=cell_polygon,
        centroid=Point(-122.205, 37.055, srid=4326),
        row=0, col=1,
    )

    # Clear any existing test data and cache
    PredictionPolygon.objects.all().delete()
    # cache.delete(CURRENT_RISK_CACHE_KEY) - no longer needed since we mock

    # Mock all sub-tasks so they do not make real network calls
    with patch("harvester.tasks.fetch_nws_alerts") as mock_nws, \
         patch("harvester.tasks.fetch_wind_data") as mock_wind, \
         patch("harvester.tasks.fetch_vegetation_indices") as mock_veg, \
         patch("harvester.tasks.fetch_goes18_imagery") as mock_goes, \
         patch("harvester.tasks.fetch_viirs_hotspots") as mock_viirs, \
         patch("harvester.tasks._call_ml_adapter", return_value=MOCK_GEOJSON_RESPONSE), \
         patch("harvester.tasks.cache.set") as mock_cache_set:

        # Configure delay() mocks so they do nothing (fire-and-forget)
        for mock_task in [mock_nws, mock_wind, mock_veg, mock_goes, mock_viirs]:
            mock_task.delay = MagicMock()

        # Run the orchestrator task synchronously (no Celery worker needed)
        result = trigger_daily_inference.apply()

    # --- Assert DB writes ---
    predictions = PredictionPolygon.objects.all()
    assert predictions.count() == 2, (
        f"Expected 2 PredictionPolygon rows (one per fixture feature), got {predictions.count()}"
    )

    high_risk = predictions.filter(grid_id=1001).first()
    assert high_risk is not None, "Expected a HIGH_RISK prediction for grid_id=1001"
    assert abs(high_risk.fire_probability - 0.91) < 0.001
    assert high_risk.source_model == "mock"
    assert high_risk.lead_time_hours == 24
    assert "timestamp" not in high_risk.ml_metrics
    assert "source_model" not in high_risk.ml_metrics

    medium_risk = predictions.filter(grid_id=1002).first()
    assert medium_risk is not None, "Expected a MODERATE_RISK prediction for grid_id=1002"

    # --- Assert Redis cache write ---
    assert mock_cache_set.called, (
        "Expected Redis cache to be populated after harvest"
    )
    args, kwargs = mock_cache_set.call_args
    assert args[0] == "ffwai:predictions:current"
    cached_geojson = json.loads(args[1])
    assert cached_geojson["type"] == "FeatureCollection"
    assert len(cached_geojson["features"]) == 2

    # --- Assert task returned success ---
    assert result.result["status"] == "success"
    assert result.result["predictions_written"] == 2

@pytest.mark.django_db
def test_gee_fetch_tasks_mock_bypass(settings):
    """
    Verifies that both fetch_goes18_imagery() and fetch_viirs_hotspots()
    correctly use the DRY _get_gee_bounding_box() helper, build the GEE logic,
    and BYPASS the final export.start() call when MOCK_INFERENCE=True.
    """
    from django.contrib.gis.geos import Polygon, Point
    from grid.models import BayAreaGrid
    from harvester.tasks import fetch_goes18_imagery, fetch_viirs_hotspots, fetch_vegetation_indices
    from unittest.mock import patch, MagicMock

    settings.GEE_PROJECT_ID = "test-project"
    settings.MOCK_INFERENCE = True

    # Seed one grid cell so Extent() returns a valid bounding box
    BayAreaGrid.objects.create(
        id=1001,
        geometry=Polygon(((-122.2, 37.0), (-122.1, 37.0), (-122.1, 37.1), (-122.2, 37.1), (-122.2, 37.0))),
        centroid=Point(-122.15, 37.05),
        row=0, col=0
    )

    # Patch sys.modules["ee"] since it is imported locally inside the tasks
    with patch.dict("sys.modules", {"ee": MagicMock()}) as mock_modules:
        mock_ee = mock_modules["ee"]
        
        # Configure the mock collection so it doesn't exit early on .size() == 0
        mock_collection = MagicMock()
        mock_collection.filterBounds.return_value = mock_collection
        mock_collection.filterDate.return_value = mock_collection
        mock_collection.size.return_value.getInfo.return_value = 1
        mock_ee.ImageCollection.return_value = mock_collection

        mock_task = MagicMock()
        mock_ee.batch.Export.image.toCloudStorage.return_value = mock_task

        # --- Test GOES-18 ---
        fetch_goes18_imagery.apply()
        # Assert GEE was initialized with ADC project ID
        mock_ee.Initialize.assert_called_with(project="test-project")
        # Assert the export task was BUILT
        mock_ee.batch.Export.image.toCloudStorage.assert_called()
        # Assert the export task was NOT STARTED
        mock_task.start.assert_not_called()
        
        # --- Test Vegetation Indices ---
        fetch_vegetation_indices.apply()
        mock_ee.Initialize.assert_called_with(project="test-project")
        # Vegetation doesn't export to GCS, it calculates NDVI and bypasses
        
        # Reset mocks for next run
        mock_ee.reset_mock()
        mock_task.reset_mock()
        
        # --- Test VIIRS ---
        fetch_viirs_hotspots.apply()
        mock_ee.Initialize.assert_called_with(project="test-project")
        mock_ee.batch.Export.image.toCloudStorage.assert_called()
        mock_task.start.assert_not_called()
        
        # --- Test Vegetation Indices ---
        fetch_vegetation_indices.apply()
        mock_ee.Initialize.assert_called_with(project="test-project")
        # Vegetation doesn't export to GCS, it calculates NDVI and bypasses


@pytest.mark.django_db
def test_trigger_active_inference_scout():
    """
    Verifies that trigger_active_inference queries the FIRMS feed,
    filters for coordinates in the Bay Area, and correctly calculates
    the 1km x 1km bounding box for async inference fan-out.
    """
    from harvester.tasks import trigger_active_inference
    
    mock_csv = "latitude,longitude\n37.5,-122.0\n35.0,-120.0\n"
    
    class MockResponse:
        def __init__(self, text, status_code=200):
            self.text = text
            self.status_code = status_code
            
        def raise_for_status(self):
            if self.status_code != 200:
                import requests
                raise requests.RequestException("Mock error")
            
    with patch("harvester.tasks.requests.get", return_value=MockResponse(mock_csv)), \
         patch("harvester.tasks.run_async_inference.delay") as mock_run_async:
             
        result = trigger_active_inference.apply()
         
        assert result.result["status"] == "success"
        assert result.result["fires_detected"] == 1
         
        # Assert run_async_inference.delay was called once with the correct bbox
        mock_run_async.assert_called_once()
        bbox = mock_run_async.call_args[0][0]
        model_type = mock_run_async.call_args[0][1]
         
        assert model_type == "unet"
        # 37.5 lat, -122.0 lon -> bounding box
        # lon - 0.0055 = -122.0055
        # lat - 0.0045 = 37.4955
        # lon + 0.0055 = -121.9945
        # lat + 0.0045 = 37.5045
        assert bbox == [-122.0055, 37.4955, -121.9945, 37.5045]

@pytest.mark.django_db
def test_trigger_active_inference_scout_fallback():
    """
    Verifies that trigger_active_inference falls back to mock data
    if the FIRMS API request fails.
    """
    from harvester.tasks import trigger_active_inference
    
    class MockResponse:
        def raise_for_status(self):
            import requests
            raise requests.RequestException("Network error")
            
    with patch("harvester.tasks.requests.get", return_value=MockResponse()), \
         patch("harvester.tasks.run_async_inference.delay") as mock_run_async:
             
        result = trigger_active_inference.apply()
         
        assert result.result["status"] == "success"
        assert result.result["fires_detected"] == 2  # The mock fallback has 2 points
        assert mock_run_async.call_count == 2

@pytest.mark.django_db
def test_trigger_active_inference_malformed_row():
    """
    Verifies that trigger_active_inference skips malformed rows in the CSV
    but successfully processes the valid ones.
    """
    from harvester.tasks import trigger_active_inference
    
    mock_csv = "latitude,longitude\n37.5,-122.0\nbad,data\n37.6,-122.1\n"
    
    class MockResponse:
        def __init__(self, text, status_code=200):
            self.text = text
            self.status_code = status_code
        def raise_for_status(self):
            pass
            
    with patch("harvester.tasks.requests.get", return_value=MockResponse(mock_csv)), \
         patch("harvester.tasks.run_async_inference.delay") as mock_run_async:
             
        result = trigger_active_inference.apply()
         
        assert result.result["status"] == "success"
        assert result.result["fires_detected"] == 2
        assert mock_run_async.call_count == 2

@pytest.mark.django_db
def test_trigger_active_inference_missing_headers():
    """
    Verifies that trigger_active_inference falls back to mock data
    if the CSV headers are missing.
    """
    from harvester.tasks import trigger_active_inference
    
    mock_csv = "lat,lon\n37.5,-122.0\n37.6,-122.1\n"
    
    class MockResponse:
        def __init__(self, text, status_code=200):
            self.text = text
            self.status_code = status_code
        def raise_for_status(self):
            pass
            
    with patch("harvester.tasks.requests.get", return_value=MockResponse(mock_csv)), \
         patch("harvester.tasks.run_async_inference.delay") as mock_run_async:
             
        result = trigger_active_inference.apply()
         
        assert result.result["status"] == "success"
        assert result.result["fires_detected"] == 2
        # It should fallback to mock data since headers are missing
        # The mock fallback also has 2 points
        assert mock_run_async.call_count == 2


@pytest.mark.django_db
def test_archive_old_predictions():
    """
    Verifies that archive_old_predictions correctly deletes PredictionPolygon
    records older than 30 days and leaves newer records intact.
    """
    from harvester.tasks import archive_old_predictions
    from predictions.models import PredictionPolygon
    from grid.models import BayAreaGrid
    from django.contrib.gis.geos import Polygon, Point
    from datetime import datetime, timedelta, timezone

    # Seed grid
    cell_polygon = Polygon((
        (-122.2, 37.0), (-122.1, 37.0), (-122.1, 37.1), (-122.2, 37.1), (-122.2, 37.0)
    ), srid=4326)
    grid = BayAreaGrid.objects.create(
        id=2001, geometry=cell_polygon,
        centroid=Point(-122.15, 37.05, srid=4326),
        row=0, col=0,
    )

    now = datetime.now(timezone.utc)
    # Create 31 days old prediction (should be deleted)
    PredictionPolygon.objects.create(
        grid_id=2001, timestamp=now - timedelta(days=31),
        source_model="mock", fire_probability=0.5
    )
    # Create 29 days old prediction (should be kept)
    PredictionPolygon.objects.create(
        grid_id=2001, timestamp=now - timedelta(days=29),
        source_model="mock", fire_probability=0.5
    )
    # Create current prediction (should be kept)
    PredictionPolygon.objects.create(
        grid_id=2001, timestamp=now,
        source_model="mock", fire_probability=0.5
    )

    assert PredictionPolygon.objects.count() == 3

    result = archive_old_predictions.apply()
    
    assert result.result["status"] == "success"
    assert result.result["deleted_count"] == 1
    assert PredictionPolygon.objects.count() == 2
