"""
Harvester Integration Tests — Fight Fire With AI

Tests the full trigger_daily_inference() happy path:
  1. Mocks the FastAPI ML Adapter HTTP response.
  2. Verifies FireRiskPrediction rows are written to the test PostGIS database.
  3. Verifies the full GeoJSON is written to the Redis cache.

ffwai-django-celery skill: require unit tests for Celery task failure states
and happy-path verification that predictions land in DB + Redis.

Design Doc §11.1 AI & Data Pipeline Testing: verify mock mode serves fixture
and that data ingestion writes correct prediction rows.

Run with:
    cd backend && pytest harvester/tests.py -v
"""

import json
from unittest.mock import patch, MagicMock

import pytest
from django.core.cache import cache

from harvester.tasks import trigger_daily_inference, store_geojson_result, CURRENT_RISK_CACHE_KEY


# ---------------------------------------------------------------------------
# Mock GeoJSON fixture (matches bay_area_fixture.json output contract)
# ---------------------------------------------------------------------------

MOCK_GEOJSON_RESPONSE = {
    "type": "FeatureCollection",
    "metadata": {
        "timestamp": "2026-09-23T06:00:00+00:00",
        "source_model": "mock",
        "mock": True,
    },
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [[
                    [-122.22, 37.05], [-122.21, 37.05],
                    [-122.21, 37.06], [-122.22, 37.06],
                    [-122.22, 37.05],
                ]],
            },
            "properties": {
                "grid_id": 1001,
                "fire_probability": 0.91,
                "risk_label": "HIGH_RISK",
                "source_model": "mock",
                "timestamp": "2026-09-23T06:00:00+00:00",
            },
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [[
                    [-122.21, 37.05], [-122.20, 37.05],
                    [-122.20, 37.06], [-122.21, 37.06],
                    [-122.21, 37.05],
                ]],
            },
            "properties": {
                "grid_id": 1002,
                "fire_probability": 0.45,
                "risk_label": "MEDIUM_RISK",
                "source_model": "mock",
                "timestamp": "2026-09-23T06:00:00+00:00",
            },
        },
    ],
}


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.mark.django_db(transaction=True)
def test_trigger_daily_inference_happy_path():
    """
    Verifies the full trigger_daily_inference() happy path:
      - Seeds the BayAreaGrid rows required to satisfy the FK constraint on
        FireRiskPrediction.grid_id (grid_id 1001 and 1002 must exist before
        the task can write predictions for them).
      - Mocks the FastAPI ML Adapter to return MOCK_GEOJSON_RESPONSE.
      - Asserts that FireRiskPrediction rows are created in the test DB.
      - Asserts the full GeoJSON is stored in the Redis cache under
        the correct key.

    Design Doc §11.1 AI & Data Pipeline Testing.
    ffwai-django-celery skill: happy-path verification, predictions in DB + Redis.
    """
    from django.contrib.gis.geos import Polygon, Point
    from grid.models import BayAreaGrid
    from predictions.models import FireRiskPrediction

    # Seed BayAreaGrid rows that the FK constraint on FireRiskPrediction.grid_id
    # requires. In production these are generated by `python manage.py generate_grid`.
    cell_polygon = Polygon((
        (-122.22, 37.05), (-122.21, 37.05),
        (-122.21, 37.06), (-122.22, 37.06),
        (-122.22, 37.05),
    ), srid=4326)
    grid_1001 = BayAreaGrid.objects.create(
        id=1001, geometry=cell_polygon,
        centroid=Point(-122.215, 37.055, srid=4326),
        row=0, col=0,
    )
    grid_1002 = BayAreaGrid.objects.create(
        id=1002, geometry=cell_polygon,
        centroid=Point(-122.205, 37.055, srid=4326),
        row=0, col=1,
    )

    # Clear any existing test data and cache
    FireRiskPrediction.objects.all().delete()
    cache.delete(CURRENT_RISK_CACHE_KEY)

    # Mock all sub-tasks so they do not make real network calls
    with patch("harvester.tasks.fetch_nws_alerts") as mock_nws, \
         patch("harvester.tasks.fetch_wind_data") as mock_wind, \
         patch("harvester.tasks.fetch_vegetation_indices") as mock_veg, \
         patch("harvester.tasks.fetch_goes18_imagery") as mock_goes, \
         patch("harvester.tasks.fetch_viirs_hotspots") as mock_viirs, \
         patch("harvester.tasks._call_ml_adapter", return_value=MOCK_GEOJSON_RESPONSE):

        # Configure delay() mocks so they do nothing (fire-and-forget)
        for mock_task in [mock_nws, mock_wind, mock_veg, mock_goes, mock_viirs]:
            mock_task.delay = MagicMock()

        # Run the orchestrator task synchronously (no Celery worker needed)
        result = trigger_daily_inference.apply()

    # --- Assert DB writes ---
    predictions = FireRiskPrediction.objects.all()
    assert predictions.count() == 2, (
        f"Expected 2 FireRiskPrediction rows (one per fixture feature), got {predictions.count()}"
    )

    high_risk = predictions.filter(grid_id=1001).first()
    assert high_risk is not None, "Expected a HIGH_RISK prediction for grid_id=1001"
    assert abs(high_risk.fire_probability - 0.91) < 0.001
    assert high_risk.risk_label == "HIGH_RISK"
    assert high_risk.source_model == "mock"

    medium_risk = predictions.filter(grid_id=1002).first()
    assert medium_risk is not None, "Expected a MEDIUM_RISK prediction for grid_id=1002"
    assert medium_risk.risk_label == "MEDIUM_RISK"

    # --- Assert Redis cache write ---
    cached_raw = cache.get(CURRENT_RISK_CACHE_KEY)
    assert cached_raw is not None, (
        f"Expected Redis cache key '{CURRENT_RISK_CACHE_KEY}' to be populated after harvest"
    )
    cached_geojson = json.loads(cached_raw)
    assert cached_geojson["type"] == "FeatureCollection"
    assert len(cached_geojson["features"]) == 2

    # --- Assert task returned success ---
    assert result.result["status"] == "success"
    assert result.result["predictions_written"] == 2

@pytest.mark.django_db
def test_gee_fetch_tasks_mock_bypass(settings):
    """
    Verifies that both fetch_goes18_imagery() and fetch_viirs_hotspots()
    correctly use the DRY _get_gee_bounding_box() helper, build the GEE logic,
    and BYPASS the final export.start() call when MOCK_INFERENCE=True.
    """
    from django.contrib.gis.geos import Polygon, Point
    from grid.models import BayAreaGrid
    from harvester.tasks import fetch_goes18_imagery, fetch_viirs_hotspots, fetch_vegetation_indices
    from unittest.mock import patch, MagicMock

    settings.GEE_PROJECT_ID = "test-project"
    settings.MOCK_INFERENCE = True

    # Seed one grid cell so Extent() returns a valid bounding box
    BayAreaGrid.objects.create(
        id=1001,
        geometry=Polygon(((-122.2, 37.0), (-122.1, 37.0), (-122.1, 37.1), (-122.2, 37.1), (-122.2, 37.0))),
        centroid=Point(-122.15, 37.05),
        row=0, col=0
    )

    # Patch sys.modules["ee"] since it is imported locally inside the tasks
    with patch.dict("sys.modules", {"ee": MagicMock()}) as mock_modules:
        mock_ee = mock_modules["ee"]
        
        # Configure the mock collection so it doesn't exit early on .size() == 0
        mock_collection = MagicMock()
        mock_collection.filterBounds.return_value = mock_collection
        mock_collection.filterDate.return_value = mock_collection
        mock_collection.size.return_value.getInfo.return_value = 1
        mock_ee.ImageCollection.return_value = mock_collection

        mock_task = MagicMock()
        mock_ee.batch.Export.image.toCloudStorage.return_value = mock_task

        # --- Test GOES-18 ---
        fetch_goes18_imagery.apply()
        # Assert GEE was initialized with ADC project ID
        mock_ee.Initialize.assert_called_with(project="test-project")
        # Assert the export task was BUILT
        mock_ee.batch.Export.image.toCloudStorage.assert_called()
        # Assert the export task was NOT STARTED
        mock_task.start.assert_not_called()
        
        # --- Test Vegetation Indices ---
        fetch_vegetation_indices.apply()
        mock_ee.Initialize.assert_called_with(project="test-project")
        # Vegetation doesn't export to GCS, it calculates NDVI and bypasses
        
        # Reset mocks for next run
        mock_ee.reset_mock()
        mock_task.reset_mock()
        
        # --- Test VIIRS ---
        fetch_viirs_hotspots.apply()
        mock_ee.Initialize.assert_called_with(project="test-project")
        mock_ee.batch.Export.image.toCloudStorage.assert_called()
        mock_task.start.assert_not_called()
        
        # --- Test Vegetation Indices ---
        fetch_vegetation_indices.apply()
        mock_ee.Initialize.assert_called_with(project="test-project")
        # Vegetation doesn't export to GCS, it calculates NDVI and bypasses
